<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="Database" Id="{605d332b-7be9-43a5-a170-f4dde6c122d7}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Database
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Database">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>