<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="POUPOU" Id="{995a384b-0e51-4c7e-aa8e-9ba6c0096ea3}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK POUPOU
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="POUPOU">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>